//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manage_Tasks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int ID { get; set; }
        public int ImageSize { get; set; }
        public string FileName { get; set; }
        public byte[] Image1 { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public string LastModifiedByUserID { get; set; }
        public System.DateTime LastModifiedOnDate { get; set; }
        public Nullable<int> ID_User { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
