//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manage_Tasks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskCreatorUser
    {
        public int ID { get; set; }
        public int TaskID { get; set; }
        public Nullable<int> CreatorID { get; set; }
        public int UserID { get; set; }
        public string Name { get; set; }
    
        public virtual TaskConfig TaskConfig { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
