//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manage_Tasks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskConfig
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaskConfig()
        {
            this.DocumentsCreated = new HashSet<DocumentsCreated>();
            this.RequestTime = new HashSet<RequestTime>();
            this.TaskCreatorUser = new HashSet<TaskCreatorUser>();
        }
    
        public int TaskID { get; set; }
        public string TaskName { get; set; }
        public string TaskDescription { get; set; }
        public string Keywords { get; set; }
        public System.DateTime TaskBeginDate { get; set; }
        public System.DateTime TaskEndDate { get; set; }
        public Nullable<bool> IsAccepted { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public System.DateTime LastModifiedOnDate { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public Nullable<int> AcceptedByUserId { get; set; }
        public Nullable<int> CompletedByUserId { get; set; }
        public Nullable<System.DateTime> DateWhenCompleted { get; set; }
        public Nullable<System.DateTime> DateWhenAccepted { get; set; }
        public bool Pending { get; set; }
        public Nullable<bool> IsRequestAccepted { get; set; }
        public string LastModifiedByUserID { get; set; }
        public Nullable<int> CreatorsGroupId { get; set; }
        public string CreatedByUserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentsCreated> DocumentsCreated { get; set; }
        public virtual Group Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestTime> RequestTime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskCreatorUser> TaskCreatorUser { get; set; }
    }
}
